# Generated by Django 3.2 on 2022-02-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocNow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='soc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
