# Generated by Django 4.0.1 on 2022-02-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocNow', '0002_auto_20220203_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancetests',
            name='name_convention',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
